Computer Science 499/599 (CS599-001, CS499-008) at Northern Arizona
University, Fall 2020

Topic: Unsupervised Learning

Dates: Aug 12 - Nov 25.

Meeting time/place: MWF 8-8:50AM, Gateway Stdnt Success, Rm 103. All
on zoom until Fri Aug 28. Hybrid in person / zoom starting Mon Aug 31.

Syllabus: [[https://docs.google.com/document/d/1HOQYWLvwsGBVijQxvXKxf8aDREeLgklCsN9L1M8bHuQ/edit?usp=sharing][Google Doc]].

Please use [[https://forms.gle/NzaR9ANXhcojRnxA6][this Google Form]] for feedback after every class.

** Textbooks

Murphy
- Author's web page https://www.cs.ubc.ca/~murphyk/MLbook/
- NAU library page https://arizona-nau-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01NAU_ALMA51166833980003842&context=L&vid=01NAU&lang=en_US&search_scope=Everything&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,murphy%20machine%20learning&sortby=rank&mode=Basic
- Link to e-book http://eds.a.ebscohost.com/ehost/ebookviewer/ebook?sid=f4a68ba6-099a-4015-9d63-a342771786f3%40sdc-v-sessmgr02&vid=0&format=EB

Hastie, Tibshirani, Friedman
- Free PDF available from author's web page
  https://web.stanford.edu/~hastie/ElemStatLearn/

** Video Lectures / Class recordings

[[https://drive.google.com/drive/folders/1PeTZJ29HRTM6BrsHTSHAdDfwZit8yA-P?usp=sharing][Folder of all class recordings on google drive]].

- Weds Aug 12: introductory [[file:2020-08-12-applications/slides.pdf][slides]].
- Fri Aug 14: [[https://www.youtube.com/watch?v=SRdzg-gzKXs&list=PLwc48KSH3D1M78ilQi35KPe2GHa7B_Rme&index=2&t=0s][video to watch before class]], reading CSV,
  str, help, subset, conversion.
- Mon Aug 17: [[https://uc-r.github.io/ggplot_intro][ggplot intro (read before class)]].
- Wed Aug 19: [[https://r4ds.had.co.nz/data-visualisation.html][Data visualization chapter of R for Data Science
  (read before class)]].
- Fri Aug 21: [[http://members.cbio.mines-paristech.fr/~thocking/animint2-manual/Ch02-ggplot2.html][Grammar of graphics chapter of Animint2 Manual (read
  before class)]].

** Homeworks

To do the homeworks you need to install [[https://cloud.r-project.org/][the most recent version of R]]
(4.0.2) with either the [[https://rstudio.com/products/rstudio/download/][RStudio]] IDE (for beginners) or the [[http://ess.r-project.org/][ESS]] IDE
(for students who already know/use emacs, or who want to learn, [[https://www.youtube.com/playlist?list=PLwc48KSH3D1Onsed66FPLywMSIQmAhUYJ][my
emacs tutorials]]).

- [[file:homeworks/1.org][1: installing R and reading CSV]] Due Fri Aug 14, 11:59PM.
- [[file:homeworks/2.org][2: data visualization using ggplot2]] Due Fri Aug 21, 11:59PM.
- TODO

General Questions and Answers
- can I do my homework with an older version of R? Maybe, try it if
  you want, but homeworks will typically require using R packages,
  which are only tested with the most recent versions of R, so if you
  are getting errors with an old version of R, try upgrading to the
  most recent version.

** How to ace this class

Before class you should prepare by doing the suggested
readings/videos. When you do that, write a summary in your own words
of every section. Also write questions that you have during your
reading so you can ask in class or office hours.

During class, take notes by writing what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please come to office hours (see
syllabus), or email me to schedule a meeting.

** Student in-person class assignment 

*** Monday	

Donnelly	Brian
Keefe	Chris
Stenberg	Alyssa
Ray	Brigham
Wan	Hui
Drake	Daniel
Kruse	Joshua
Shaffer	Isaac
Cao	Kehan

*** Wednesday	

Rovira-Sugranes	Arnau
Kethireddy	Sambashiva Reddy
Hillman	Jonathan
Su	Weiheng
Couey	Benjamin
Rao	Jun
Messenger	Zachary
Ghanaimiandoab	Dina
Peterson	Benjamin
Nemeth	Thomas
Bolyen	Evan

*** friday 

everyone remote/zoom.
