Computer Science 499/599 (CS599-001, CS499-008) at Northern Arizona
University, Fall 2020

Topic: Unsupervised Learning

Dates: Aug 12 - Nov 25.

Meeting time/place: MWF 8-8:50AM, Gateway Stdnt Success, Rm 103. All
on zoom until Fri Aug 28. Hybrid in person / zoom starting Mon Aug 31.

Syllabus: [[https://docs.google.com/document/d/1HOQYWLvwsGBVijQxvXKxf8aDREeLgklCsN9L1M8bHuQ/edit?usp=sharing][Google Doc]].

Please use [[https://forms.gle/NzaR9ANXhcojRnxA6][this Google Form]] for feedback after every class.

** Textbooks

Murphy
- Author's web page https://www.cs.ubc.ca/~murphyk/MLbook/
- NAU library page https://arizona-nau-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01NAU_ALMA51166833980003842&context=L&vid=01NAU&lang=en_US&search_scope=Everything&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,murphy%20machine%20learning&sortby=rank&mode=Basic
- Link to e-book http://eds.a.ebscohost.com/ehost/ebookviewer/ebook?sid=f4a68ba6-099a-4015-9d63-a342771786f3%40sdc-v-sessmgr02&vid=0&format=EB

Hastie, Tibshirani, Friedman
- Free PDF available from author's web page
  https://web.stanford.edu/~hastie/ElemStatLearn/

** Video Lectures / Class recordings

- Weds Aug 12: [[file:2020-08-12-applications/slides.pdf][slides]]
- Fri Aug 14: [[https://www.youtube.com/watch?v=SRdzg-gzKXs&list=PLwc48KSH3D1M78ilQi35KPe2GHa7B_Rme&index=2&t=0s][video to watch before class]]
- TODO

** Homeworks

- [[file:homeworks/1.org]] Due Fri Aug 14, 11:59PM.
- TODO

** How to ace this class

Before class you should read the suggested book chapters. When you
read, write a summary in your own words of every paragraph or
section. Also write questions that you have during your reading so you
can ask in class (if related to the lecture topic) or in office hours.

During class, instead of copying what I write on the whiteboard, I
would suggest to try to write what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please drop by my office hours
(see syllabus), or email me to schedule a meeting.

** Student in-person class assignment 

Monday	Donnelly	Brian
Monday	Keefe	Chris
Monday	Stenberg	Alyssa
Monday	Ray	Brigham
Monday	Wan	Hui
Monday	Drake	Daniel
Monday	Kruse	Joshua
Monday	Rovira-Sugranes	Arnau
Monday	Shaffer	Isaac
Monday	Cao	Kehan
Wednesday	Kethireddy	Sambashiva Reddy
Wednesday	Hillman	Jonathan
Wednesday	Su	Weiheng
Wednesday	Couey	Benjamin
Wednesday	Rao	Jun
Wednesday	Messenger	Zachary
Wednesday	Ghanaimiandoab	Dina
Wednesday	Peterson	Benjamin
Wednesday	Nemeth	Thomas
Wednesday	Bolyen	Evan

(friday will be all-remote)
