Computer Science 499 and 599 at Northern Arizona University, Fall 2020

Topic: Unsupervised Learning

Dates: Aug 24 - Dec 11.

Meeting time/place: TBD

Syllabi: [[file:CS499-Fall2020-Unsupervised-Learning-Syllabus.pdf][499]], [[file:CS599-Fall2020-Unsupervised-Learning-Syllabus.pdf][599]].

** Textbooks

Murphy
- Author's web page https://www.cs.ubc.ca/~murphyk/MLbook/
- NAU library page https://arizona-nau-primo.hosted.exlibrisgroup.com/primo-explore/fulldisplay?docid=01NAU_ALMA51166833980003842&context=L&vid=01NAU&lang=en_US&search_scope=Everything&adaptor=Local%20Search%20Engine&tab=default_tab&query=any,contains,murphy%20machine%20learning&sortby=rank&mode=Basic
- Link to e-book http://eds.a.ebscohost.com/ehost/ebookviewer/ebook?sid=f4a68ba6-099a-4015-9d63-a342771786f3%40sdc-v-sessmgr02&vid=0&format=EB

Hastie, Tibshirani, Friedman
- Free PDF available from author's web page
  https://web.stanford.edu/~hastie/ElemStatLearn/

** Screencasts

To learn basic R programming skills which will be highly relevant to
your coding projects in this class, please watch [[https://www.youtube.com/playlist?list=PLwc48KSH3D1M78ilQi35KPe2GHa7B_Rme][these screencasts]] and
follow along (pause the videos, type the code, then and execute the
code on your own computer).

** Lectures

TODO

** Coding projects

TODO

** How to ace this class

Before class you should read the suggested book chapters. When you
read, write a summary in your own words of every paragraph or
section. Also write questions that you have during your reading so you
can ask in class (if related to the lecture topic) or in office hours.

During class, instead of copying what I write on the whiteboard, I
would suggest to try to write what you understood in your own
words. Also I would suggest to ask questions in class as soon as you
need clarification.

After class, you should review your notes with one of your classmates
(ask one of the students who seem to be correctly answering a lot of
questions). Ask each other questions and try to teach/summarize some
of the material with each other -- that is one of the best ways to
learn.

Finally after doing all of the above, please drop by my office hours
(see syllabus), or email me to schedule a meeting.

